# Generated by Django 3.2.12 on 2022-05-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance', models.CharField(max_length=1000)),
                ('sql_query', models.CharField(default='', editable=False, max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
