# Generated by Django 3.2.12 on 2022-04-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='translated_statement',
            field=models.CharField(default='', editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='translation',
            name='sql_statement',
            field=models.CharField(default='sql statement', editable=False, max_length=100),
        ),
    ]
