# Generated by Django 3.2.12 on 2022-05-17 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220423_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='nl_question',
            new_name='utterance',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='translated_statement',
        ),
    ]
