# Generated by Django 3.2.12 on 2022-05-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220517_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='sql_statement',
        ),
        migrations.AddField(
            model_name='translation',
            name='sql_query',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
