# Generated by Django 3.2.7 on 2022-03-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('date_hired', models.DateField(verbose_name='date hired')),
                ('is_working', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('DOB', models.DateField(verbose_name='date of birth')),
                ('NHS_num', models.IntegerField()),
                ('BMI', models.IntegerField()),
                ('admitted', models.BooleanField()),
                ('location_admitted', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlidb.patients')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlidb.medicalstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlidb.patients')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlidb.medicalstaff')),
            ],
        ),
    ]
