# Generated by Django 3.2.12 on 2022-06-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('DOB', models.DateField(verbose_name='date of birth')),
                ('NHS_num', models.IntegerField()),
                ('BMI', models.IntegerField()),
                ('admitted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('date_hired', models.DateField(verbose_name='date hired')),
                ('is_working', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nlidb.patient')),
                ('date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlidb.staff')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlidb.treatment')),
            ],
            options={
                'unique_together': {('patient', 'staff', 'date_time')},
            },
        ),
    ]
