# Generated by Django 3.2.7 on 2022-03-02 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlidb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalstaff',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='id',
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='staff_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='patients',
            name='patient_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nlidb.patients'),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nlidb.patients'),
        ),
        migrations.AlterUniqueTogether(
            name='appointments',
            unique_together={('patient', 'staff')},
        ),
        migrations.AlterUniqueTogether(
            name='treatments',
            unique_together={('patient', 'staff')},
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='id',
        ),
        migrations.RemoveField(
            model_name='treatments',
            name='id',
        ),
    ]
