# Generated by Django 3.2.12 on 2022-06-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlidb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nlidb.treatment'),
        ),
    ]
