# Generated by Django 3.2.12 on 2022-06-18 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlidb', '0002_alter_appointment_treatment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='is_working',
            new_name='working',
        ),
    ]
