# Generated by Django 3.2.12 on 2022-04-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlidb', '0002_auto_20220302_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.RenameModel(
            old_name='Treatments',
            new_name='Treatment',
        ),
    ]
