# Generated by Django 3.2.12 on 2022-05-18 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlidb', '0005_alter_patient_ward_admitted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalStaff',
            new_name='Staff',
        ),
    ]
